# Generated by Django 2.1.7 on 2019-03-14 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
            ],
            options={
                'db_table': 'payments',
            },
        ),
    ]
